# GNUmakefile

PACKAGE_DIR=..

mods_todomvc_SWIFT_FILES = \
  $(wildcard Sources/*.swift) \
  $(wildcard Sources/CalDAV/*.swift)

mods_todomvc_LIBS = ApacheExpress

include $(PACKAGE_DIR)/mod_swift/xcconfig/rules.make
